### ISSUE TITLE
Версия 3.00 не совместима с Eresus 3.01

### ISSUE THREAD

**Issue by mekras** [Eresus/Gallery#4]
```
Argument 1 passed to Gallery_ClientListView::getMaxCount() must be an instance of Plugin, instance of Gallery given, called in /usr/home/www/eresus/unstable/ext/gallery/classes/ClientListView.php on line 59 and defined
Backtrace:
#0 /usr/home/www/eresus/unstable/ext/gallery/classes/ClientListView.php(132): Eresus_Kernel::errorHandler(4096, 'Argument 1 pass...', '/usr/home/www/e...', 132, Array)
#1 /usr/home/www/eresus/unstable/ext/gallery/classes/ClientListView.php(59): Gallery_ClientListView->getMaxCount(Object(Gallery))
#2 /usr/home/www/eresus/unstable/ext/gallery.php(1029): Gallery_ClientListView->render()
#3 /usr/home/www/eresus/unstable/ext/gallery.php(479): Gallery->clientRenderList()
#4 /usr/home/www/eresus/unstable/core/Plugin/Registry.php(342): Gallery->clientRenderContent()
#5 /usr/home/www/eresus/unstable/core/client.php(389): Eresus_Plugin_Registry->clientRenderContent(Object(Eresus_CMS_Request))
#6 /usr/home/www/eresus/unstable/core/Client/FrontController.php(48): TClientUI->render(Object(Eresus_CMS_Request))
#7 /usr/home/www/eresus/unstable/core/CMS.php(339): Eresus_Client_FrontController->dispatch()
#8 /usr/home/www/eresus/unstable/core/CMS.php(121): Eresus_CMS->runWeb()
#9 /usr/home/www/eresus/unstable/core/Kernel.php(510): Eresus_CMS->main()
#10 /usr/home/www/eresus/unstable/index.php(83): Eresus_Kernel::exec('Eresus_CMS')
#11 {main}
```

**Comment by mekras** [comment]
Исправлено.
